name: "Build"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-24.04

    env:
      EXPAT_VERSION: 2.4.4

    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1", "5.2", "5.3", "5.4", "luajit-2.1.0-beta3", "luajit-openresty"]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - uses: leafo/gh-actions-lua@6919171ccf181b826f44b9bca76307b577217377 # v13.0.0
      with:
        luaVersion: ${{ matrix.luaVersion }}

    - uses: leafo/gh-actions-luarocks@35d062def313a7699a0d513e996bcf4352f05389 # v6.1.0

    - name: build expat
      run: |
        git clone -b R_$(echo $EXPAT_VERSION | sed "s/\./_/g") --single-branch https://github.com/libexpat/libexpat.git
        cd libexpat/expat
        ./buildconf.sh
        ./configure
        sudo make install

    - name: Lua dependencies
      run: |
        git config --global url.https://github.com/.insteadOf git://github.com/
        luarocks install busted
        luarocks install luacov-coveralls

    - name: build
      run: |
        luarocks make

    - name: Busted tests
      run: |
        busted --coverage --Xoutput "--color"

    - name: Report test coverage
      if: success()
      continue-on-error: true
      run: luacov-coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ github.token }}
